"""
Minecraft 模组术语库 — 社区公认译名对照

添加/修改术语后自动生效，所有翻译器共享此表。
"""

# 格式: { "英文原文": "简体中文译名" }
# 注意：key 区分大小写，匹配时不区分（会同时匹配大小写变体）
TERMS = {
    # === 原版方块 ===
    "Crafting Table": "工作台",
    "Furnace": "熔炉",
    "Blast Furnace": "高炉",
    "Smoker": "烟熏炉",
    "Anvil": "铁砧",
    "Enchanting Table": "附魔台",
    "Brewing Stand": "酿造台",
    "Beacon": "信标",
    "Conduit": "潮涌核心",
    "Respawn Anchor": "重生锚",
    "Ender Chest": "末影箱",
    "Shulker Box": "潜影盒",
    "Chest": "箱子",
    "Barrel": "木桶",
    "Hopper": "漏斗",
    "Dispenser": "发射器",
    "Dropper": "投掷器",
    "Observer": "侦测器",
    "Piston": "活塞",
    "Sticky Piston": "粘性活塞",
    "Redstone Dust": "红石粉",
    "Redstone Torch": "红石火把",
    "Redstone Repeater": "红石中继器",
    "Redstone Comparator": "红石比较器",
    "Daylight Detector": "阳光探测器",
    "TNT": "TNT",
    "Note Block": "音符盒",
    "Jukebox": "唱片机",
    "Lever": "拉杆",
    "Button": "按钮",
    "Pressure Plate": "压力板",
    "Tripwire Hook": "绊线钩",
    "Trapped Chest": "陷阱箱",
    "Iron Door": "铁门",
    "Oak Door": "橡木门",
    "Trapdoor": "活板门",
    "Fence Gate": "栅栏门",
    "Ladder": "梯子",
    "Scaffolding": "脚手架",
    "Bed": "床",
    "Door": "门",
    "Fence": "栅栏",
    "Wall": "墙",
    "Slab": "台阶",
    "Stairs": "楼梯",
    "Glass Pane": "玻璃板",
    "Iron Bars": "铁栏杆",

    # === 原版物品 ===
    "Pickaxe": "镐",
    "Axe": "斧",
    "Shovel": "锹",
    "Hoe": "锄",
    "Sword": "剑",
    "Bow": "弓",
    "Crossbow": "弩",
    "Trident": "三叉戟",
    "Shield": "盾牌",
    "Arrow": "箭",
    "Spectral Arrow": "光灵箭",
    "Tipped Arrow": "药箭",
    "Fishing Rod": "钓鱼竿",
    "Carrot on a Stick": "胡萝卜钓竿",
    "Warped Fungus on a Stick": "诡异菌钓竿",
    "Shears": "剪刀",
    "Flint and Steel": "打火石",
    "Fire Charge": "火焰弹",
    "Bucket": "桶",
    "Water Bucket": "水桶",
    "Lava Bucket": "熔岩桶",
    "Milk Bucket": "牛奶桶",
    "Powder Snow Bucket": "细雪桶",
    "Lead": "拴绳",
    "Name Tag": "命名牌",
    "Saddle": "鞍",
    "Minecart": "矿车",
    "Chest Minecart": "运输矿车",
    "Furnace Minecart": "动力矿车",
    "Hopper Minecart": "漏斗矿车",
    "TNT Minecart": "TNT矿车",
    "Boat": "船",
    "Elytra": "鞘翅",
    "Totem of Undying": "不死图腾",
    "Ender Pearl": "末影珍珠",
    "Eye of Ender": "末影之眼",
    "Ender Eye": "末影之眼",
    "Firework Rocket": "烟花火箭",
    "Firework Star": "烟火之星",
    "Bone Meal": "骨粉",
    "Book": "书",
    "Enchanted Book": "附魔书",
    "Book and Quill": "书与笔",
    "Written Book": "成书",
    "Map": "地图",
    "Empty Map": "空地图",
    "Compass": "指南针",
    "Clock": "时钟",
    "Recovery Compass": "追溯指针",

    # === 矿石与材料 ===
    "Coal": "煤炭",
    "Coal Ore": "煤矿石",
    "Charcoal": "木炭",
    "Iron Ingot": "铁锭",
    "Iron Ore": "铁矿石",
    "Iron Nugget": "铁粒",
    "Raw Iron": "粗铁",
    "Gold Ingot": "金锭",
    "Gold Ore": "金矿石",
    "Gold Nugget": "金粒",
    "Raw Gold": "粗金",
    "Diamond": "钻石",
    "Diamond Ore": "钻石矿石",
    "Netherite Ingot": "下界合金锭",
    "Netherite Scrap": "下界合金碎片",
    "Ancient Debris": "远古残骸",
    "Emerald": "绿宝石",
    "Emerald Ore": "绿宝石矿石",
    "Lapis Lazuli": "青金石",
    "Lapis Lazuli Ore": "青金石矿石",
    "Redstone": "红石",
    "Redstone Ore": "红石矿石",
    "Copper Ingot": "铜锭",
    "Copper Ore": "铜矿石",
    "Raw Copper": "粗铜",
    "Nether Quartz": "下界石英",
    "Nether Quartz Ore": "下界石英矿石",
    "Amethyst Shard": "紫水晶碎片",
    "Amethyst Cluster": "紫水晶簇",
    "Flint": "燧石",
    "Clay": "粘土",
    "Clay Ball": "粘土球",
    "Brick": "砖",
    "Nether Brick": "下界砖",
    "Prismarine Shard": "海晶碎片",
    "Prismarine Crystals": "海晶砂粒",
    "Blaze Rod": "烈焰棒",
    "Blaze Powder": "烈焰粉",
    "Ender Pearl": "末影珍珠",
    "Ghast Tear": "恶魂之泪",
    "Gunpowder": "火药",
    "Glowstone Dust": "荧石粉",
    "Glowstone": "荧石",
    "Slimeball": "粘液球",
    "Magma Cream": "岩浆膏",
    "Spider Eye": "蜘蛛眼",
    "Fermented Spider Eye": "发酵蛛眼",
    "Phantom Membrane": "幻翼膜",
    "Rabbit Hide": "兔子皮",
    "Rabbit's Foot": "兔子脚",
    "Leather": "皮革",
    "Feather": "羽毛",
    "Ink Sac": "墨囊",
    "Glow Ink Sac": "荧光墨囊",
    "Honeycomb": "蜜脾",
    "Honey Bottle": "蜂蜜瓶",
    "Nautilus Shell": "鹦鹉螺壳",
    "Heart of the Sea": "海洋之心",
    "Scute": "鳞甲",
    "Nether Star": "下界之星",
    "Dragon Egg": "龙蛋",
    "Dragon Breath": "龙息",
    "Shulker Shell": "潜影壳",
    "Music Disc": "音乐唱片",
    "Echo Shard": "回响碎片",
    "Disc Fragment": "唱片残片",

    # === 生物 ===
    "Creeper": "苦力怕",
    "Zombie": "僵尸",
    "Skeleton": "骷髅",
    "Spider": "蜘蛛",
    "Cave Spider": "洞穴蜘蛛",
    "Enderman": "末影人",
    "Slime": "史莱姆",
    "Ghast": "恶魂",
    "Blaze": "烈焰人",
    "Witch": "女巫",
    "Wither Skeleton": "凋灵骷髅",
    "Wither": "凋灵",
    "Guardian": "守卫者",
    "Elder Guardian": "远古守卫者",
    "Silverfish": "蠹虫",
    "Endermite": "末影螨",
    "Magma Cube": "岩浆怪",
    "Shulker": "潜影贝",
    "Phantom": "幻翼",
    "Drowned": "溺尸",
    "Husk": "尸壳",
    "Stray": "流髑",
    "Pillager": "掠夺者",
    "Vindicator": "卫道士",
    "Evoker": "唤魔者",
    "Ravager": "劫掠兽",
    "Vex": "恼鬼",
    "Piglin": "猪灵",
    "Piglin Brute": "猪灵蛮兵",
    "Hoglin": "疣猪兽",
    "Zoglin": "僵尸疣猪兽",
    "Zombified Piglin": "僵尸猪灵",
    "Strider": "炽足兽",
    "Warden": "监守者",
    "Iron Golem": "铁傀儡",
    "Snow Golem": "雪傀儡",
    "Villager": "村民",
    "Wandering Trader": "流浪商人",
    "Wolf": "狼",
    "Cat": "猫",
    "Ocelot": "豹猫",
    "Horse": "马",
    "Donkey": "驴",
    "Mule": "骡",
    "Llama": "羊驼",
    "Trader Llama": "行商羊驼",
    "Pig": "猪",
    "Cow": "牛",
    "Mooshroom": "哞菇",
    "Sheep": "羊",
    "Chicken": "鸡",
    "Rabbit": "兔子",
    "Squid": "鱿鱼",
    "Glow Squid": "发光鱿鱼",
    "Turtle": "海龟",
    "Dolphin": "海豚",
    "Axolotl": "美西螈",
    "Goat": "山羊",
    "Frog": "青蛙",
    "Tadpole": "蝌蚪",
    "Allay": "悦灵",
    "Sniffer": "嗅探兽",
    "Camel": "骆驼",
    "Armadillo": "犰狳",
    "Breeze": "旋风人",
    "Bogged": "沼骸",
    "Bat": "蝙蝠",
    "Parrot": "鹦鹉",
    "Fox": "狐狸",
    "Polar Bear": "北极熊",
    "Panda": "熊猫",
    "Bee": "蜜蜂",

    # === 维度与群系 ===
    "Overworld": "主世界",
    "Nether": "下界",
    "The End": "末地",
    "End": "末地",
    "Plains": "平原",
    "Desert": "沙漠",
    "Forest": "森林",
    "Taiga": "针叶林",
    "Swamp": "沼泽",
    "Jungle": "丛林",
    "Savanna": "热带草原",
    "Badlands": "恶地",
    "Mesa": "恶地",
    "Mushroom Fields": "蘑菇岛",
    "Ocean": "海洋",
    "River": "河流",
    "Beach": "沙滩",
    "Mountain": "山地",
    "Snowy Tundra": "积雪的冻原",
    "Ice Spikes": "冰刺平原",
    "Dark Forest": "黑森林",
    "Birch Forest": "白桦森林",
    "Bamboo Jungle": "竹林",
    "Cherry Grove": "樱花树林",
    "Mangrove Swamp": "红树林沼泽",
    "Deep Dark": "深暗之域",
    "Dripstone Caves": "溶洞",
    "Lush Caves": "繁茂洞穴",
    "Crimson Forest": "绯红森林",
    "Warped Forest": "诡异森林",
    "Soul Sand Valley": "灵魂沙峡谷",
    "Basalt Deltas": "玄武岩三角洲",
    "The Void": "虚空",

    # === 结构 ===
    "Village": "村庄",
    "Desert Temple": "沙漠神殿",
    "Jungle Temple": "丛林神庙",
    "Stronghold": "要塞",
    "End Portal": "末地传送门",
    "Nether Portal": "下界传送门",
    "Nether Fortress": "下界要塞",
    "Bastion Remnant": "堡垒遗迹",
    "Pillager Outpost": "掠夺者前哨站",
    "Woodland Mansion": "林地府邸",
    "Ocean Monument": "海底神殿",
    "Ocean Ruins": "海底废墟",
    "Shipwreck": "沉船",
    "Buried Treasure": "埋藏的宝藏",
    "Ruined Portal": "废弃传送门",
    "Mineshaft": "废弃矿井",
    "Dungeon": "地牢",
    "Igloo": "雪屋",
    "Witch Hut": "女巫小屋",
    "Swamp Hut": "沼泽小屋",
    "Ancient City": "远古城市",
    "Trail Ruins": "古迹废墟",
    "Trial Chambers": "试炼密室",

    # === 常见模组术语 ===
    "Quest": "任务",
    "Quests": "任务",
    "Quest Book": "任务书",
    "Quest Line": "任务线",
    "Chapter": "章节",
    "Reward": "奖励",
    "Claim Reward": "领取奖励",
    "Complete": "完成",
    "Completed": "已完成",
    "Objective": "目标",
    "Requirement": "前置条件",
    "Dependency": "依赖",
    "Repeatable": "可重复",
    "Reset": "重置",
    "Submit": "提交",
    "Task": "任务",
    "Checkmark": "勾选",
    "Check": "勾选",
    "Craft": "合成",
    "Smelt": "烧炼",
    "Brew": "酿造",
    "Smith": "锻造",
    "Enchant": "附魔",
    "Enchantment": "附魔",
    "Enchanted": "已附魔",
    "Repair": "修复",
    "Tool": "工具",
    "Weapon": "武器",
    "Armor": "护甲",
    "Armour": "护甲",
    "Helmet": "头盔",
    "Chestplate": "胸甲",
    "Leggings": "护腿",
    "Boots": "靴子",
    "Tier": "等级",
    "Tiers": "等级",
    "Stage": "阶段",
    "Stages": "阶段",
    "Progression": "进度",
    "Advancement": "进度",
    "Achievement": "成就",
    "Unlock": "解锁",
    "Locked": "已锁定",
    "Automation": "自动化",
    "Generator": "发电机",
    "Generator Block": "发电机方块",
    "Energy": "能量",
    "Power": "能量",
    "RF": "RF",
    "FE": "FE",
    "EU": "EU",
    "MJ": "MJ",
    "Redstone Flux": "红石通量",
    "Forge Energy": "FE能量",
    "Fluid": "流体",
    "Gas": "气体",
    "Input": "输入",
    "Output": "输出",
    "Slot": "槽位",
    "Tank": "储罐",
    "Pipe": "管道",
    "Cable": "线缆",
    "Conduit": "导管",
    "Duct": "管道",
    "Facade": "伪装板",
    "Filter": "过滤器",
    "Upgrade": "升级",
    "Augment": "增强",
    "Capacitor": "电容",
    "Battery": "电池",
    "Buffer": "缓存器",
    "Processor": "处理器",
    "Circuit": "电路",
    "Gear": "齿轮",
    "Plate": "板",
    "Rod": "杆",
    "Coil": "线圈",
    "Casing": "外壳",
    "Frame": "框架",
    "Housing": "外壳",
    "Wrench": "扳手",
    "Hammer": "锤子",
    "Cutter": "切割器",
    "Screwdriver": "螺丝刀",
    "Crowbar": "撬棍",
    "Multimeter": "万用表",
    "Void": "虚空",
    "Automated": "自动化",
    "Manual": "手动",
    "Click": "点击",
    "Right Click": "右键",
    "Right-click": "右键",
    "Left Click": "左键",
    "Shift": "潜行",
    "Sneak": "潜行",
    "Sneaking": "潜行",
    "Jump": "跳跃",
    "Sprint": "冲刺",
    "Fly": "飞行",
    "Swim": "游泳",

    # === FTB 常用模组名 ===
    "Create": "机械动力",
    "Thermal Expansion": "热力膨胀",
    "Thermal Foundation": "热力基本",
    "Thermal Dynamics": "热动力学",
    "Thermal Cultivation": "热力农业",
    "Thermal Innovation": "热力革新",
    "Thermal Locomotion": "热力运输",
    "Applied Energistics": "应用能源",
    "Applied Energistics 2": "应用能源2",
    "AE2": "AE2",
    "Refined Storage": "精致存储",
    "Mekanism": "通用机械",
    "Immersive Engineering": "沉浸工程",
    "Botania": "植物魔法",
    "Mana": "魔力",
    "Mana Pool": "魔力池",
    "Mana Spreader": "魔力扩散器",
    "Mana Tablet": "魔力石板",
    "Mana Ring": "魔力指环",
    "Blood Magic": "血魔法",
    "Life Essence": "生命源质",
    "Blood Altar": "血之祭坛",
    "Thaumcraft": "神秘时代",
    "Thaumcraft 6": "神秘时代6",
    "Vis": "魔力",
    "Flux": "咒波",
    "Aura": "灵气",
    "Aspect": "要素",
    "Tinkers' Construct": "匠魂",
    "Tinkers Construct": "匠魂",
    "TConstruct": "匠魂",
    "Smeltery": "冶炼炉",
    "Tool Forge": "工具装配台",
    "Part Builder": "部件加工台",
    "Stencil Table": "模具加工台",
    "Pattern": "模具",
    "Cast": "铸模",
    "IndustrialCraft": "工业时代",
    "IndustrialCraft 2": "工业时代2",
    "IC2": "IC2",
    "BuildCraft": "建筑",
    "Quarry": "采石场",
    "Forestry": "林业",
    "Railcraft": "铁路",
    "ComputerCraft": "电脑",
    "CC:Tweaked": "CC:Tweaked",
    "OpenComputers": "开放式电脑",
    "PneumaticCraft": "气动工艺",
    "RFTools": "RF工具",
    "RFTools Dimensions": "RF工具：维度",
    "Draconic Evolution": "龙之进化",
    "Draconium": "龙素",
    "Ender IO": "末影接口",
    "Extra Utilities": "更多实用设备",
    "Extra Utilities 2": "更多实用设备2",
    "Random Things": "随意之作",
    "Quark": "夸克",
    "Biomes O' Plenty": "超多生物群系",
    "BOP": "超多生物群系",
    "Oh The Biomes You'll Go": "你将去的生物群系",
    "BYG": "BYG",
    "Twilight Forest": "暮色森林",
    "Aether": "天境",
    "The Aether": "天境",
    "Galacticraft": "星系",
    "Advanced Rocketry": "高级火箭",
    "ProjectE": "等价交换",
    "Project E": "等价交换",
    "EMC": "EMC",
    "Energy Matter Covalence": "能量物质共价",
    "Mystical Agriculture": "神秘农业",
    "Mystical Agradditions": "神秘农业扩展",
    "Essence": "精华",
    "Inferium": "下级精华",
    "Prudentium": "初级精华",
    "Intermedium": "中级精华",
    "Superium": "高级精华",
    "Supremium": "终极精华",
    "Insanium": "究极精华",
    "Ex Nihilo": "无中生有",
    "Ex Nihilo: Sequentia": "无中生有：传承",
    "Ex Compressum": "压缩",
    "Skyblock": "空岛",
    "Sky Block": "空岛",
    "Stoneblock": "石岛",
    "Stone Block": "石岛",
    "KubeJS": "KubeJS",
    "CraftTweaker": "合成修改器",
    "ZenScript": "ZenScript",
    "Patchouli": "帕秋莉手册",
    "Guide Book": "指南书",
    "Guidebook": "指南书",
    "Manual": "手册",
    "Lexica Botania": "植物魔法辞典",
    "FTB Quests": "FTB任务",
    "FTB Teams": "FTB队伍",
    "FTB Chunks": "FTB区块",
    "JEI": "JEI",
    "Just Enough Items": "JEI物品管理器",
    "REI": "REI",
    "Roughly Enough Items": "REI物品管理器",
    "EMI": "EMI",
    "WAILA": "WAILA",
    "HWYLA": "HWYLA",
    "Jade": "Jade",
    "The One Probe": "The One Probe",
    "TOP": "TOP",
    "JourneyMap": "旅行地图",
    "Xaero's World Map": "Xaero的世界地图",
    "Xaero's Minimap": "Xaero的小地图",
    "Waypoint": "路径点",
    "Waystone": "传送石碑",
    "Teleport": "传送",
    "Teleporter": "传送器",

    # === 常见药水效果 ===
    "Speed": "速度",
    "Slowness": "缓慢",
    "Haste": "急迫",
    "Mining Fatigue": "挖掘疲劳",
    "Strength": "力量",
    "Instant Health": "瞬间治疗",
    "Instant Damage": "瞬间伤害",
    "Jump Boost": "跳跃提升",
    "Nausea": "反胃",
    "Regeneration": "生命恢复",
    "Resistance": "抗性提升",
    "Fire Resistance": "防火",
    "Water Breathing": "水下呼吸",
    "Invisibility": "隐身",
    "Blindness": "失明",
    "Night Vision": "夜视",
    "Hunger": "饥饿",
    "Weakness": "虚弱",
    "Poison": "中毒",
    "Wither": "凋零",
    "Health Boost": "生命提升",
    "Absorption": "伤害吸收",
    "Saturation": "饱和",
    "Glowing": "发光",
    "Levitation": "飘浮",
    "Luck": "幸运",
    "Bad Luck": "霉运",
    "Slow Falling": "缓降",
    "Conduit Power": "潮涌能量",
    "Dolphin's Grace": "海豚的恩惠",
    "Darkness": "黑暗",
    "Hero of the Village": "村庄英雄",
    "Bad Omen": "不祥之兆",
    "Raid Omen": "袭击之兆",
    "Trial Omen": "试炼之兆",
    "Ominous": "不祥",
    "Wind Burst": "风爆",
    "Weaving": "蓄风",
    "Oozing": "渗浆",
    "Infested": "寄生",
    "Density": "沉重",
    "Breach": "穿透",

    # === 原版附魔 ===
    "Protection": "保护",
    "Fire Protection": "火焰保护",
    "Feather Falling": "摔落保护",
    "Blast Protection": "爆炸保护",
    "Projectile Protection": "弹射物保护",
    "Respiration": "水下呼吸",
    "Aqua Affinity": "水下速掘",
    "Thorns": "荆棘",
    "Depth Strider": "深海探索者",
    "Frost Walker": "冰霜行者",
    "Curse of Binding": "绑定诅咒",
    "Sharpness": "锋利",
    "Smite": "亡灵杀手",
    "Bane of Arthropods": "节肢杀手",
    "Knockback": "击退",
    "Fire Aspect": "火焰附加",
    "Looting": "抢夺",
    "Sweeping Edge": "横扫之刃",
    "Efficiency": "效率",
    "Silk Touch": "精准采集",
    "Unbreaking": "耐久",
    "Fortune": "时运",
    "Power": "力量",
    "Punch": "冲击",
    "Flame": "火矢",
    "Infinity": "无限",
    "Luck of the Sea": "海之眷顾",
    "Lure": "饵钓",
    "Loyalty": "忠诚",
    "Impaling": "穿刺",
    "Riptide": "激流",
    "Channeling": "引雷",
    "Multishot": "多重射击",
    "Quick Charge": "快速装填",
    "Piercing": "穿透",
    "Mending": "经验修补",
    "Curse of Vanishing": "消失诅咒",
    "Soul Speed": "灵魂疾行",
    "Swift Sneak": "迅捷潜行",

    # === 颜色与装饰 ===
    "White": "白色",
    "Orange": "橙色",
    "Magenta": "品红色",
    "Light Blue": "淡蓝色",
    "Yellow": "黄色",
    "Lime": "黄绿色",
    "Pink": "粉红色",
    "Gray": "灰色",
    "Light Gray": "淡灰色",
    "Cyan": "青色",
    "Purple": "紫色",
    "Blue": "蓝色",
    "Brown": "棕色",
    "Green": "绿色",
    "Red": "红色",
    "Black": "黑色",

    # === 其他常用 ===
    "Mob": "生物",
    "Mobs": "生物",
    "Spawn": "生成",
    "Spawner": "刷怪笼",
    "Spawn Egg": "刷怪蛋",
    "Monster Spawner": "刷怪笼",
    "Drop": "掉落物",
    "Drops": "掉落物",
    "Loot": "战利品",
    "Loot Table": "战利品表",
    "Chest Loot": "箱子战利品",
    "XP": "经验值",
    "Experience": "经验值",
    "Experience Points": "经验值",
    "Level": "等级",
    "Levels": "等级",
    "Durability": "耐久度",
    "Stack": "堆叠",
    "Stack Size": "堆叠数量",
    "Block": "方块",
    "Blocks": "方块",
    "Item": "物品",
    "Items": "物品",
    "Entity": "实体",
    "Tile Entity": "方块实体",
    "Block Entity": "方块实体",
    "Chunk": "区块",
    "Chunk Loader": "区块加载器",
    "Tick": "刻",
    "Ticks": "刻",
    "Redstone Tick": "红石刻",
    "Game Tick": "游戏刻",
    "FPS": "帧率",
    "TPS": "TPS",
    "Server": "服务器",
    "Client": "客户端",
    "Singleplayer": "单人游戏",
    "Multiplayer": "多人游戏",
    "LAN": "局域网",
    "Config": "配置",
    "Configuration": "配置",
    "Settings": "设置",
    "Options": "选项",
    "Keybind": "按键绑定",
    "Keybinding": "按键绑定",
    "Hotkey": "快捷键",
    "Modpack": "整合包",
    "Mod": "模组",
    "Mods": "模组",
    "Resource Pack": "资源包",
    "Data Pack": "数据包",
    "Shader": "光影",
    "Shader Pack": "光影包",
    "Forge": "Forge",
    "NeoForge": "NeoForge",
    "Fabric": "Fabric",
    "Quilt": "Quilt",
    "Mod Loader": "模组加载器",
    "Addon": "附属",
    "Add-on": "附属",
    "DLC": "DLC",
    "Plugin": "插件",
}

def parse_markdown_glossary(path: str) -> dict:
    """
    解析 translation_glossary.md，提取所有英文→中文术语对。

    支持三种表格格式：
      | English | 中文 | 备注 |       (3 列，取 col 0→1)
      | English | 中文 |              (2 列)
      | 英文 | 错误译法 | 正确译法 | 说明 | (4 列「翻译陷阱」，取 col 0→2)
    跳过无管道符的行、表头分隔行 (---)。
    """
    import re
    import os
    terms = {}
    if not os.path.exists(path):
        return terms

    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    for line in lines:
        stripped = line.strip()
        if not stripped.startswith('|'):
            continue
        if re.match(r'^\|[\s\-:]+\|', stripped):  # 分隔行
            continue

        cols = [c.strip() for c in stripped.split('|')]
        # 去掉首尾空元素
        cols = [c for c in cols if c]

        if len(cols) < 2:
            continue

        en = cols[0]
        # 跳过标题行 / 纯中文的表头
        if en in ('English', '英文', '代码'):
            continue

        # 4 列陷阱表：英文 | 错误译法 | 正确译法 | 说明  → 取 col 0→2
        # 2-3 列常规表：English | 中文 [| 备注]          → 取 col 0→1
        if len(cols) >= 4:
            zh = cols[2]
        else:
            zh = cols[1]

        # 清理 null/空值、纯标点
        if zh and zh.lower() != 'null' and zh != '-' and en:
            terms[en] = zh

    return terms


def _load_glossary_path():
    import os
    return os.path.join(os.path.dirname(__file__), '..', 'translation_glossary.md')


# 合并术语：Markdown 排在前面（确保不被 max_terms 截断），硬编码兜底
def _load_merged_terms():
    md_terms = parse_markdown_glossary(_load_glossary_path())
    merged = dict(md_terms)       # Markdown 先占位，优先级高
    for k, v in TERMS.items():
        if k not in merged:
            merged[k] = v
    return merged


# 生成提示词中使用的术语表文本
def build_glossary_prompt(max_terms: int = 120) -> str:
    """
    Markdown 术语全部保留，剩余配额用硬编码原版术语填补。
    """
    md_terms = parse_markdown_glossary(_load_glossary_path())
    merged = _load_merged_terms()
    hardcoded = [(k, v) for k, v in merged.items() if k not in md_terms]

    entries = list(md_terms.items())
    remaining = max_terms - len(entries)
    if remaining > 0:
        entries += hardcoded[:remaining]
    if len(entries) > max_terms:
        entries = entries[:max_terms]

    lines = []
    for en, zh in entries:
        lines.append(f"  \"{en}\" -> \"{zh}\"")
    glossary = "\n".join(lines)
    return (
        "IMPORTANT — Minecraft Community Standard Translation Glossary: "
        "The following English terms MUST be translated using the EXACT community-accepted Chinese translations shown below. "
        "These translations are the de facto standards used by the Minecraft Chinese community and official game localization:\n"
        f"{glossary}\n"
        "If the text contains any of these terms, use the translations listed above exactly as written.\n"
    )
